## Numpy: Number Python

In [5]:
#not numpy
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#import numpy
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
type(np.array([1,2,3,4,5])[1])

numpy.int32

In [8]:
np.array([np.pi,4,2,3])

array([3.14159265, 4.        , 2.        , 3.        ])

In [10]:
type(np.array([np.pi,4,2,3])[2])

numpy.float64

In [12]:
np.array([np.pi,4,2,3],dtype='float32')

array([3.1415927, 4.       , 2.       , 3.       ], dtype=float32)

In [14]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [16]:
np.array([1,2,'a'])

array(['1', '2', 'a'], dtype='<U11')

In [18]:
#multidimensional array
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Create arrays from scratch

In [20]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
p = np.ones([2, 3], int) #integers
p

array([[1, 1, 1],
       [1, 1, 1]])

In [26]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [28]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 10, stepping by 1
print(np.arange(0, 10, 1))

# compared to the built-in range() function
print(list(range(0,10)))

[0 1 2 3 4 5 6 7 8 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [30]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
#repeat
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [34]:
#this also works
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [36]:
help(np.repeat)

Help on _ArrayFunctionDispatcher in module numpy:

repeat(a, repeats, axis=None)
    Repeat each element of an array after themselves

    Parameters
    ----------
    a : array_like
        Input array.
    repeats : int or array of ints
        The number of repetitions for each element.  `repeats` is broadcasted
        to fit the shape of the given axis.
    axis : int, optional
        The axis along which to repeat values.  By default, use the
        flattened input array, and return a flat output array.

    Returns
    -------
    repeated_array : ndarray
        Output array which has the same shape as `a`, except along
        the given axis.

    See Also
    --------
    tile : Tile an array.
    unique : Find the unique elements of an array.

    Examples
    --------
    >>> np.repeat(3, 4)
    array([3, 3, 3, 3])
    >>> x = np.array([[1,2],[3,4]])
    >>> np.repeat(x, 2)
    array([1, 1, 2, 2, 3, 3, 4, 4])
    >>> np.repeat(x, 3, axis=1)
    array([[1, 1, 1, 2, 2, 2],

In [38]:
x = np.array([[1,2],[3,4]])
np.repeat(x, [1, 2], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])

In [40]:
np.repeat(x, [1, 2], axis=1)

array([[1, 2, 2],
       [3, 4, 4]])

## Distribution generator

In [42]:
# uniformly distributed
# random values between 0 and 1
np.random.random(10)

array([0.44437825, 0.90080496, 0.30348691, 0.63457457, 0.79095963,
       0.0523428 , 0.93142281, 0.73096623, 0.07768404, 0.99785979])

In [44]:
np.random.random((2,4)) #specify the shape

array([[9.72429890e-01, 3.96592232e-01, 7.25878411e-02, 8.82412991e-01],
       [9.21510576e-02, 2.25354636e-01, 5.56822838e-01, 3.47334376e-04]])

In [46]:
# normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.69823366, -0.26789473, -2.4805508 ],
       [ 0.19251298, -0.73031029,  1.52454089],
       [ 0.08213618, -1.07612222,  0.30366899]])

In [48]:
# random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[5, 2, 0],
       [7, 2, 8],
       [2, 3, 2]])

In [50]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
# Create an uninitialized array of given shape and type
# `empty`, unlike `zeros`, does not set the array values to zero,
# and may therefore be marginally faster.
np.empty((3,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.11260280e-306],
       [6.00801178e-307, 8.90108992e-307]])

## Numpy data types
Data Type Description <br>
bool_ Boolean (True or False) stored as a byte <br>
int_ Default integer type (same as C long; normally either int64 or int32) <br>
intc Identical to C int (normally int32 or int64) <br>
intp Integer used for indexing (same as C ssize_t; normally either int32 or int64) <br>
int8 Byte (–128 to 127) <br>
int16 Integer (–32768 to 32767) <br>
int32 Integer (–2147483648 to 2147483647) <br>
int64 Integer (–9223372036854775808 to 9223372036854775807) <br>
uint8 Unsigned integer (0 to 255) <br>
uint16 Unsigned integer (0 to 65535) <br>
uint32 Unsigned integer (0 to 4294967295) <br>
uint64 Unsigned integer (0 to 18446744073709551615) <br>
float_ Shorthand for float64 <br>
float16 Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa <br>
float32 Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa <br>
float64 Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa <br>
complex_ Shorthand for complex128 <br>
complex64 Complex number, represented by two 32-bit floats <br>
complex128 Complex number, represented by two 64-bit floats <br>

## Attributes of arrays
Determining the size, shape, memory consumption, and data types of arrays

In [25]:
import numpy as np
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [62]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [64]:
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


## Indexing of arrays
Getting and setting the value of individual array elements

In [66]:
print(x1)

[5 0 3 3 7 9]


In [68]:
print(x1[0])
print(x1[4])
print(x1[-1])
print(x1[-2])

5
7
9
7


In [70]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [72]:
x2[0,0]

3

In [74]:
x2[0,-1]

4

In [76]:
#mutable
x2[0,0] = 9
x2

array([[9, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [80]:
#unchanged type; modified values
x1[0]=np.pi
x1

array([3, 0, 3, 3, 7, 9])

## Slicing of arrays
Getting and setting smaller subarrays within a larger array

In [82]:
x = np.arange(0, 10, 1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
x[:5] # first five elements; not include index 5(6th)

array([0, 1, 2, 3, 4])

In [86]:
x[5:] # elements since index 5(6th)

array([5, 6, 7, 8, 9])

In [88]:
x[4:7]  #start:stop:step

array([4, 5, 6])

In [90]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [92]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [94]:
x[1::3]

array([1, 4, 7])

In [96]:
x[1::1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
x[:-1] # does not include -1, the last one

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [100]:
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [102]:
x[5::-1] # reversed from index 5

array([5, 4, 3, 2, 1, 0])

In [104]:
x[5:-1] # normal order

array([5, 6, 7, 8])

In [106]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

In [108]:
x[7::-3] # reversed every 3 from index 7

array([7, 4, 1])

Exercise: return every other element of x, starting at index 4

In [110]:
##your answer
x[4::2]

array([4, 6, 8])

### slicing of multidimensional arrays

In [112]:
x2

array([[9, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [114]:
x2[0:2,0:3] # two rows, three columns

array([[9, 5, 2],
       [7, 6, 8]])

In [116]:
x2[:,:3]

array([[9, 5, 2],
       [7, 6, 8],
       [1, 6, 7]])

In [124]:
x2[:, ::2] # all rows, every other column

array([[9, 2],
       [7, 8],
       [1, 7]])

In [126]:
x2[::-1,::-1] #reverse 

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 9]])

In [130]:
x2[:,0]

array([9, 7, 1])

In [132]:
#in row access, column can be omitted; NOT vice versa
print(x2[0,:]) 

[9 5 2 4]


In [134]:
print(x2[0]) # equivalent to x2[0, :]

[9 5 2 4]


In [136]:
print(x2[0,])

[9 5 2 4]


In [138]:
x2[:,0]

array([9, 7, 1])

In [140]:
x2[,0] #error

SyntaxError: invalid syntax (1836097955.py, line 1)

In [142]:
x2

array([[9, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [144]:
x2 > 5

array([[ True, False, False, False],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]])

In [146]:
#conditional indexing
x2[x2 > 5]

array([9, 7, 6, 8, 8, 6, 7, 7])

In [148]:
x2[x2 > 5] = 0
x2

array([[0, 5, 2, 4],
       [0, 0, 0, 0],
       [1, 0, 0, 0]])

In [150]:
x2[x2 == 5]

array([5])

In [152]:
x2[x2 != 5]

array([0, 2, 4, 0, 0, 0, 0, 1, 0, 0, 0])

In [154]:
x2[x2 > 5]

array([], dtype=int32)

In [156]:
x2[x2 >= 5]

array([5])

In [158]:
x2[x2 < 5]

array([0, 2, 4, 0, 0, 0, 0, 1, 0, 0, 0])

In [160]:
x2[x2 <= 5]

array([0, 5, 2, 4, 0, 0, 0, 0, 1, 0, 0, 0])

Exercise: create an integer array 'y' of the same shape as x2. The array element for y should show value 1 if the corresponding x2 element at the same position is 0, otherwise the array element for y should show value 0.

i.e. y should be:
[[1, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 1, 1, 1]]

In [165]:
#your answer
y =np.zeros((3,4),dtype='int')
y[x2==0]=1
y

array([[1, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 1, 1, 1]])

### No copy views of subarrays

In [27]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [29]:
x2_sub = x2[:2, :2]
x2_sub

array([[3, 5],
       [7, 6]])

In [31]:
x2_sub[0, 0] = 100
x2_sub

array([[100,   5],
       [  7,   6]])

In [33]:
x2

array([[100,   5,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]])

In [35]:
#use copy() to actually copy
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy[0, 0] = -20
x2_sub_copy

array([[-20,   5],
       [  7,   6]])

In [38]:
x2

array([[100,   5,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]])

## Reshaping of arrays
Changing the shape of a given array

In [40]:
#reshape()
g = np.arange(1, 10)
grid = g.reshape(3,3)
print(g)
print(grid)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
### size match
g.reshape(2,3)

ValueError: cannot reshape array of size 9 into shape (2,3)

In [44]:
#no-copy view
grid[1,1] = 100
print(grid)
print(g)

[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]
[  1   2   3   4 100   6   7   8   9]


In [46]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [48]:
# row vector via reshape
# dimension
x.reshape((1,3))

array([[1, 2, 3]])

In [50]:
#resize() 
gg = np.arange(0, 9)
gg

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
gg.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
gg.resize(3,3)
gg

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
x

array([1, 2, 3])

In [ ]:
# row vector via newaxis
x[np.newaxis,:] 

In [ ]:
x[np.newaxis,:].shape

In [ ]:
# row vector via newaxis
x[np.newaxis,]

In [ ]:
x[:, np.newaxis]

In [ ]:
x[:, np.newaxis].shape

In [ ]:
# column vector via reshape
x = np.arange(0,6)
x.reshape(6,1)

In [ ]:
x

In [ ]:
x[::2, np.newaxis]

## Concatenating and splitting of arrays
Combining multiple arrays into one, and splitting one array into many

In [80]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [82]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [94]:
grid = np.array([[1, 2, 3],
[4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
grid.shape

(2, 3)

In [90]:
# concatenate along the first axis (zero-indexed)
np.concatenate([grid, grid],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [92]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
np.concatenate([grid, grid])

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],
[99]])
np.hstack([grid, y])

In [ ]:
#pass a list of indices giving the split point
x = [1, 2, 3, 99, 99, 3, 2, 1, 1, 2, 3]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

In [ ]:
np.split(x, [3, 5, 8])

In [ ]:
grid = np.arange(16).reshape((2, 8))
grid

In [ ]:
#along the vertical axis
upper, lower = np.vsplit(grid, [1])
print(upper)
print(lower)

In [ ]:
#along the horizontal axis
left, middle, right = np.hsplit(grid, [2,4])
print(left)
print(middle)
print(right)

### Iterating Over Arrays

5 by 3 array of random numbers 0-9: 

In [73]:
a = np.random.randint(0, 10, (5,3))
a

array([[6, 8, 2],
       [3, 0, 0],
       [6, 0, 6],
       [3, 3, 8],
       [8, 8, 2]])

In [63]:
#Iterate by row:
for row in a:
    print(row)

[4 3 4]
[4 8 4]
[3 7 5]
[5 0 1]
[5 9 3]


In [65]:
#column?
for column in np.transpose(a):
    print(column)

[4 4 3 5 5]
[3 8 7 0 9]
[4 4 5 1 3]


In [67]:
#Iterate by index:
for i in range(len(a)):
    print(a[i])

[4 3 4]
[4 8 4]
[3 7 5]
[5 0 1]
[5 9 3]


In [75]:
#Iterate by row using enumerate
list(enumerate(a))

[(0, array([6, 8, 2])),
 (1, array([3, 0, 0])),
 (2, array([6, 0, 6])),
 (3, array([3, 3, 8])),
 (4, array([8, 8, 2]))]

In [ ]:
dict(enumerate(a))

In [ ]:
for i, row in enumerate(a):
    print('row', i, 'is', row)

In [ ]:
a2 = a**2
a2

In [ ]:
#zip: iterate over multiple iterables.
list(zip(a))

In [ ]:
help(zip)

In [ ]:
for i, j in zip(a, a2):
    print(i,'+',j,'=',i+j)

In [ ]:
list(zip(a,a2))

## Operations

Use `+`, `-`, `*`, `/`,`**`... to perform element wise addition, subtraction, multiplication, division, etc.

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x)
print(y)

In [ ]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

In [ ]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise division         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

In [ ]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

In [ ]:
print(y // x) # floor_divide
print(y % x) #remainder

**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [ ]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

In [ ]:
z = np.array([y, y**2, y**3])
z # number of rows of array

### Transposing arrays: permutes the dimensions of the array

In [ ]:
z = np.array([y, y**2])
z

<br>
The shape of array `z` is `(2,3)` before transposing.

In [ ]:
z.shape

In [ ]:
#transpose:
np.transpose(z)

In [ ]:
#alternatively, transpose using T:
z.T

In [ ]:
#the shape has changed:
z.T.shape

In [ ]:
#dtype to check the data type
z.dtype

In [ ]:
#cast to a specific type
z2 = z.T.astype('f')
print(z2.dtype)
z2

## Math Functions

Numpy has built-in math functions：

In [ ]:
a = np.arange(-8,8,2).reshape(4,2)
a

In [ ]:
print(a.sum())
#sum along the row/column axis
print(a.sum(0))
print(a.sum(1)) 

In [ ]:
a.max()

In [ ]:
a.min()

In [ ]:
a.mean()

In [ ]:
a.std()

In [ ]:
#Return the index of the maximum and minimum values in the array.
a.argmax()

In [ ]:
a.argmin()

In [ ]:
##np.func() series
np.median(a)

In [ ]:
np.percentile(a,25) #25th percentile

In [ ]:
a

In [104]:
np.prod(a[1,]) #product of elements

0

In [ ]:
print(np.any(a==0))
print(np.any(a==1))

In [ ]:
print(np.all(a<8))

In [ ]:
print(np.count_nonzero(a<3))

In [ ]:
a

In [ ]:
# alternatively
# False is interpreted as 0, and True is interpreted as 1
print(np.sum(a<3))
print(np.sum(a<3, axis = 1)) # along the column axis

In [ ]:
#absolute values
print(abs(a)); print(np.abs(a));print(np.absolute(a))

In [ ]:
#trigonometric functions
theta = np.linspace(0, np.pi, 3)
print(theta)
print(np.sin(theta))
print(np.arcsin([-1,0,1]))

In [ ]:
#exponential and logarithms
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

In [ ]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

In [ ]:
?np.log

Exercise: for the two-dimensional array 'a', return the index of the maximum values for each row in the array.

### Sorting

In [ ]:
x = np.array([-4, 2, 3, 1, 5, 1])
y = x.copy().reshape(2,3)
print(x)
print(y)

In [ ]:
x.sort()
print(x)

y.sort(axis=0) #along columns
print(y)

In [ ]:
y.sort(axis=1) #along rows, shuffling columns
print(y)

In [ ]:
#reverse sorting
x[::-1].sort()
print(x)

In [ ]:
y[:,::-1].sort(axis=1)
print(y)

In [ ]:
#return the index
x = np.array([-4, 2, 3, 1, 5, 1])
print(np.argsort(x))

In [ ]:
x[np.argsort(x)]

In [ ]:
x[np.argsort(x)[::-1]]

In [ ]:
x[np.argsort(x)][::-1]